import React, { useEffect, useState } from 'react';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { Trash2, Wand2, BadgeCheck, FlaskConical } from 'lucide-react';
import { HexColorPicker } from 'react-colorful';
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover';
import type { Filament } from '../types';
import { estimateTDFromColor } from '../lib/colorUtils';
import {
    computeProfileConfidence,
    getConfidenceLabel,
    getConfidenceColor,
    sanitizeFrontlitCalibration,
} from '../lib/calibration';

interface FilamentRowProps {
    filament: Filament;
    onUpdate: (id: string, updates: Partial<Omit<Filament, 'id'>>) => void;
    onRemove: (id: string) => void;
    onCalibrate?: (id: string) => void;
}

const FilamentRow = React.memo(function FilamentRow({
    filament,
    onUpdate,
    onRemove,
    onCalibrate,
}: FilamentRowProps) {
    // Local state for the input value to allow free typing
    const [localTd, setLocalTd] = useState<string>(filament.td.toString());
    // Local state for color to allow smooth dragging without frequent parent updates
    const [localColor, setLocalColor] = useState<string>(filament.color);
    // Local state for name — auto-generates from color when no custom name is set
    const [localName, setLocalName] = useState<string>(
        filament.name ?? `Filament ${filament.color}`
    );

    // Calculate confidence for this filament
    const sanitizedCalibration = sanitizeFrontlitCalibration(filament.calibration);
    const calibrationMatchesTd =
        !!sanitizedCalibration && Math.abs(filament.td - sanitizedCalibration.tdSingleValue) < 0.05;
    const activeCalibration = calibrationMatchesTd ? sanitizedCalibration : undefined;

    const confidence = computeProfileConfidence({
        calibration: activeCalibration,
        transmissionDistance: filament.td,
    });
    const confidenceLabel = getConfidenceLabel(confidence);
    const confidenceColorClass = getConfidenceColor(confidence);
    const isCalibrated = !!activeCalibration;

    // Sync local TD state if prop changes externally
    useEffect(() => {
        setLocalTd(filament.td.toString());
    }, [filament.td]);

    // Sync local color state if prop changes externally
    useEffect(() => {
        setLocalColor(filament.color);
    }, [filament.color]);

    // Sync local name state if prop changes externally
    useEffect(() => {
        setLocalName(filament.name ?? `Filament ${localColor}`);
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [filament.name]);

    // Auto-update name from color when no custom name is set
    useEffect(() => {
        if (!filament.name) {
            setLocalName(`Filament ${localColor}`);
        }
    }, [localColor, filament.name]);

    // Debounced update for color
    useEffect(() => {
        const timer = setTimeout(() => {
            if (localColor !== filament.color) {
                onUpdate(filament.id, { color: localColor });
            }
        }, 200);
        return () => clearTimeout(timer);
    }, [localColor, filament.id, filament.color, onUpdate]);

    const handleNameBlur = () => {
        const trimmed = localName.trim();
        // If the field is empty or still matches the auto-generated value, unset name to stay in auto mode
        const autoGenerated = `Filament ${localColor}`;
        onUpdate(filament.id, { name: !trimmed || trimmed === autoGenerated ? undefined : trimmed });
    };

    const handleNameKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
        if (e.key === 'Enter') (e.target as HTMLInputElement).blur();
    };

    const handleBlur = () => {
        let val = parseFloat(localTd);
        if (isNaN(val)) {
            setLocalTd(filament.td.toString());
            return;
        }
        val = Math.min(100, Math.max(0.1, val));
        onUpdate(filament.id, { td: val, calibration: undefined });
        setLocalTd(val.toString());
    };

    const handleKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
        if (e.key === 'Enter') {
            handleBlur();
            (e.target as HTMLInputElement).blur();
        }
    };

    return (
        <div className="flex items-center gap-2 p-2 rounded-md border border-border/40 bg-card hover:border-border/80 transition-colors">
            {/* Color Picker Popover */}
            <Popover>
                <PopoverTrigger asChild>
                    <button
                        type="button"
                        className="w-8 h-8 rounded-full border-2 border-border shadow-sm flex-shrink-0 focus:outline-none focus:ring-2 focus:ring-primary/20 transition-transform hover:scale-105 cursor-pointer"
                        style={{ backgroundColor: localColor }}
                        title="Change filament color"
                    />
                </PopoverTrigger>
                <PopoverContent className="w-auto p-3" align="start">
                    <div className="space-y-3">
                        <h4 className="font-medium text-sm">Pick Color</h4>
                        <HexColorPicker color={localColor} onChange={setLocalColor} />
                        <div className="flex gap-2 items-center">
                            <span className="text-xs text-muted-foreground">Hex</span>
                            <Input
                                value={localColor}
                                onChange={(e) => setLocalColor(e.target.value)}
                                className="h-7 text-xs font-mono"
                            />
                        </div>
                    </div>
                </PopoverContent>
            </Popover>

            {/* Name Input */}
            <Input
                type="text"
                value={localName}
                onChange={(e) => setLocalName(e.target.value)}
                onBlur={handleNameBlur}
                onKeyDown={handleNameKeyDown}
                placeholder="Name"
                className="h-8 text-sm flex-1 min-w-0"
            />

            {/* Transmission Distance Input */}
            <div className="relative w-20 flex-shrink-0">
                <Input
                    type="number"
                    min={0.1}
                    max={100}
                    step={0.1}
                    value={localTd}
                    onChange={(e) => setLocalTd(e.target.value)}
                    onBlur={handleBlur}
                    onKeyDown={handleKeyDown}
                    className="h-8 text-sm pr-8"
                />
                <div className="absolute right-2 top-1/2 -translate-y-1/2 text-xs text-muted-foreground pointer-events-none">
                    TD
                </div>
            </div>

            {/* Auto-compute TD Button */}
            <Button
                variant="ghost"
                size="icon"
                onClick={() => {
                    const estimatedTd = estimateTDFromColor(localColor);
                    setLocalTd(estimatedTd.toString());
                    onUpdate(filament.id, { td: estimatedTd, calibration: undefined });
                }}
                className="h-8 w-8 text-muted-foreground hover:text-amber-600 hover:bg-amber-600/10 cursor-pointer"
                title="Auto-estimate TD from color"
            >
                <Wand2 className="w-4 h-4" />
            </Button>

            {onCalibrate && (
                <Button
                    variant="ghost"
                    size="icon"
                    onClick={() => onCalibrate(filament.id)}
                    className="h-8 w-8 text-muted-foreground hover:text-primary hover:bg-primary/10 cursor-pointer"
                    title="Calibrate filament"
                >
                    <FlaskConical className="w-4 h-4" />
                </Button>
            )}

            {/* Calibration Badge */}
            {isCalibrated && (
                <div
                    className={`flex h-8 items-center gap-1 px-2 rounded-md bg-muted/50 ${confidenceColorClass}`}
                    title={`Calibrated · Confidence: ${confidenceLabel} (${(confidence * 100).toFixed(0)}%)`}
                >
                    <BadgeCheck className="w-3 h-3" />
                    <span className="text-[10px] font-medium">{confidenceLabel}</span>
                </div>
            )}

            {/* Delete Button */}
            <Button
                variant="ghost"
                size="icon"
                onClick={() => onRemove(filament.id)}
                className="h-8 w-8 text-muted-foreground hover:text-destructive hover:bg-destructive/10 cursor-pointer"
                title="Remove filament"
            >
                <Trash2 className="w-4 h-4" />
            </Button>
        </div>
    );
});

export default FilamentRow;
