import { useTranslation } from 'react-i18next';
import React, { useEffect, useState } from 'react';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { Trash2, Wand2, BadgeCheck, ArrowRightLeft } from 'lucide-react';
import { HexColorPicker } from '@/components/ui/localized-color-picker';
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover';
import type { Filament } from '../types';
import { estimateHidingDistanceFromColor } from '../lib/colorUtils';
import { colorEditUpdateForFilament } from '../lib/filamentUpdates';
import { translateRuntimeMessage } from '../lib/runtimeMessages';
import {
    activeFrontlitCalibration,
    channelHds,
    computeProfileConfidence,
    getConfidenceLabel,
    getConfidenceColor,
    FRONTLIT_TD_SCALE,
} from '../lib/calibration';

const HD_MIN = 0.01;
const HD_MAX = 2;

interface FilamentRowProps {
    filament: Filament;
    onUpdate: (id: string, updates: Partial<Omit<Filament, 'id'>>) => void;
    onRemove: (id: string) => void;
}

const FilamentRow = React.memo(function FilamentRow({
    filament,
    onUpdate,
    onRemove,
}: FilamentRowProps) {
    const { t } = useTranslation('printing');
    // Local state for the input value to allow free typing
    const [localTd, setLocalTd] = useState<string>(filament.td.toString());
    // Local state for color to allow smooth dragging without frequent parent updates
    const [localColor, setLocalColor] = useState<string>(filament.color);
    // Local state for name — auto-generates from color when no custom name is set
    const [localName, setLocalName] = useState<string>(
        filament.name ?? `Filament ${filament.color}`
    );

    // Calculate confidence for this filament. A calibration only counts while
    // the swatch still matches the color it was measured for; editing the color
    // deactivates it (and channelHds falls back to color-derived HDs), so the
    // badge and the optical model stay consistent.
    const activeCalibration = activeFrontlitCalibration(filament);

    const confidence = computeProfileConfidence({
        calibration: activeCalibration,
        transmissionDistance: filament.td,
    });
    const confidenceLabel = translateRuntimeMessage(getConfidenceLabel(confidence));
    const confidenceColorClass = getConfidenceColor(confidence);
    const isCalibrated = !!activeCalibration;

    // Per-channel hiding distances: measured (calibrated) or derived from color.
    const channels = channelHds(filament);
    const channelText = `R ${channels[0].toFixed(2)} / G ${channels[1].toFixed(2)} / B ${channels[2].toFixed(2)} mm`;

    // "Convert from TD" popover state (conventional backlit/lithophane value).
    const [convertDraft, setConvertDraft] = useState('');
    const [convertOpen, setConvertOpen] = useState(false);

    // Sync local TD state if prop changes externally
    useEffect(() => {
        setLocalTd(filament.td.toString());
    }, [filament.td]);

    // Sync local color state if prop changes externally
    useEffect(() => {
        setLocalColor(filament.color);
    }, [filament.color]);

    // Sync local name state if prop changes externally
    useEffect(() => {
        setLocalName(filament.name ?? `Filament ${localColor}`);
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [filament.name]);

    // Auto-update name from color when no custom name is set
    useEffect(() => {
        if (!filament.name) {
            setLocalName(`Filament ${localColor}`);
        }
    }, [localColor, filament.name]);

    // Debounced update for color
    useEffect(() => {
        const timer = setTimeout(() => {
            if (localColor !== filament.color) {
                onUpdate(filament.id, colorEditUpdateForFilament(filament, localColor));
            }
        }, 200);
        return () => clearTimeout(timer);
    }, [localColor, filament, onUpdate]);

    const handleNameBlur = () => {
        const trimmed = localName.trim();
        // If the field is empty or still matches the auto-generated value, unset name to stay in auto mode
        const autoGenerated = `Filament ${localColor}`;
        const translatedDefault = t('filamentRow.defaultName', { color: localColor });
        onUpdate(filament.id, {
            name:
                !trimmed || trimmed === autoGenerated || trimmed === translatedDefault
                    ? undefined
                    : trimmed,
        });
    };

    const handleNameKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
        if (e.key === 'Enter') (e.target as HTMLInputElement).blur();
    };

    const handleBlur = () => {
        let val = parseFloat(localTd);
        if (isNaN(val)) {
            setLocalTd(filament.td.toString());
            return;
        }
        val = Math.min(HD_MAX, Math.max(HD_MIN, val));
        onUpdate(filament.id, { td: val, calibration: undefined });
        setLocalTd(val.toString());
    };

    const handleConvertFromTd = () => {
        const val = parseFloat(convertDraft);
        if (isNaN(val) || val <= 0) return;
        const hd = Math.min(
            HD_MAX,
            Math.max(HD_MIN, Math.round(val * FRONTLIT_TD_SCALE * 100) / 100)
        );
        setLocalTd(hd.toString());
        onUpdate(filament.id, { td: hd, calibration: undefined });
        setConvertDraft('');
        setConvertOpen(false);
    };

    const handleKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
        if (e.key === 'Enter') {
            handleBlur();
            (e.target as HTMLInputElement).blur();
        }
    };

    return (
        <div className="flex items-center gap-2 p-2 rounded-md border border-border/40 bg-card hover:border-border/80 transition-colors">
            {/* Color Picker Popover */}
            <Popover>
                <PopoverTrigger asChild>
                    <button
                        type="button"
                        className="w-8 h-8 rounded-full border-2 border-border shadow-sm flex-shrink-0 focus:outline-none focus:ring-2 focus:ring-primary/20 transition-transform hover:scale-105 cursor-pointer"
                        style={{ backgroundColor: localColor }}
                        title={t('filamentRow.changeFilamentColor')}
                    />
                </PopoverTrigger>
                <PopoverContent className="w-auto p-3" align="start">
                    <div className="space-y-3">
                        <h4 className="font-medium text-sm">{t('filamentRow.pickColor')}</h4>
                        <HexColorPicker color={localColor} onChange={setLocalColor} />
                        <div className="flex gap-2 items-center">
                            <span className="text-xs text-muted-foreground">
                                {t('filamentRow.hex')}
                            </span>
                            <Input
                                value={localColor}
                                onChange={(e) => setLocalColor(e.target.value)}
                                className="h-7 text-xs font-mono"
                            />
                        </div>
                    </div>
                </PopoverContent>
            </Popover>

            {/* Name Input */}
            <Input
                type="text"
                value={
                    !filament.name && localName === `Filament ${localColor}`
                        ? t('filamentRow.defaultName', { color: localColor })
                        : localName
                }
                onChange={(e) => setLocalName(e.target.value)}
                onBlur={handleNameBlur}
                onKeyDown={handleNameKeyDown}
                placeholder={t('filamentRow.name')}
                className="h-8 text-sm flex-1 min-w-0"
            />

            {/* Hiding Distance Input */}
            <div
                className="relative w-20 flex-shrink-0"
                title={t(
                    isCalibrated
                        ? 'filamentRow.measuredHidingDistance'
                        : 'filamentRow.estimatedHidingDistance',
                    { channels: channelText }
                )}
            >
                <Input
                    type="number"
                    min={HD_MIN}
                    max={HD_MAX}
                    step={0.01}
                    value={localTd}
                    onChange={(e) => setLocalTd(e.target.value)}
                    onBlur={handleBlur}
                    onKeyDown={handleKeyDown}
                    className="h-8 text-sm pr-8"
                />
                <div className="absolute right-2 top-1/2 -translate-y-1/2 text-xs text-muted-foreground pointer-events-none">
                    HD
                </div>
            </div>

            {/* Convert from conventional (backlit/lithophane) TD */}
            <Popover open={convertOpen} onOpenChange={setConvertOpen}>
                <PopoverTrigger asChild>
                    <Button
                        variant="ghost"
                        size="icon"
                        className="h-8 w-8 text-muted-foreground hover:text-primary hover:bg-primary/10 cursor-pointer"
                        title={t('filamentRow.convertFromTDLithophaneBacklitValue')}
                    >
                        <ArrowRightLeft className="w-4 h-4" />
                    </Button>
                </PopoverTrigger>
                <PopoverContent className="w-64 p-3" align="start">
                    <div className="space-y-2">
                        <h4 className="text-sm font-medium">{t('filamentRow.convertFromTD')}</h4>
                        <p className="text-[11px] text-muted-foreground">
                            {t(
                                'filamentRow.enterAConventionalTransmissionDistanceSpoolSheetOrLithophane'
                            )}
                        </p>
                        <div className="flex gap-2">
                            <Input
                                type="number"
                                min={0.1}
                                max={20}
                                step={0.1}
                                value={convertDraft}
                                onChange={(e) => setConvertDraft(e.target.value)}
                                onKeyDown={(e) => {
                                    if (e.key === 'Enter') handleConvertFromTd();
                                }}
                                placeholder={t('filamentRow.eG40')}
                                className="h-8 text-sm"
                            />
                            <Button size="sm" className="h-8" onClick={handleConvertFromTd}>
                                {t('filamentRow.convert')}
                            </Button>
                        </div>
                    </div>
                </PopoverContent>
            </Popover>

            {/* Auto-estimate HD Button */}
            <Button
                variant="ghost"
                size="icon"
                onClick={() => {
                    const estimated = estimateHidingDistanceFromColor(localColor);
                    setLocalTd(estimated.toString());
                    onUpdate(filament.id, { td: estimated, calibration: undefined });
                }}
                className="h-8 w-8 text-muted-foreground hover:text-amber-600 hover:bg-amber-600/10 cursor-pointer"
                title={t('filamentRow.autoEstimateHidingDistanceFromColor')}
            >
                <Wand2 className="w-4 h-4" />
            </Button>

            {/* Calibration status — fixed-width slot so rows stay aligned */}
            {isCalibrated ? (
                <div
                    className={`flex h-8 w-[4.75rem] flex-shrink-0 items-center justify-center gap-1 rounded-md bg-muted/50 ${confidenceColorClass}`}
                    title={t('filamentRow.calibrationStatus', {
                        confidence: confidenceLabel,
                        percentage: (confidence * 100).toFixed(0),
                        channels: channelText,
                    })}
                >
                    <BadgeCheck className="w-3 h-3 flex-shrink-0" />
                    <span className="text-[10px] font-medium truncate">{confidenceLabel}</span>
                </div>
            ) : (
                <div
                    className="flex h-8 w-[4.75rem] flex-shrink-0 items-center justify-center rounded-md border border-dashed border-border/60 text-muted-foreground/70"
                    title={t('filamentRow.uncalibratedStatus', { channels: channelText })}
                >
                    <span className="text-[10px] font-medium">{t('filamentRow.estimate')}</span>
                </div>
            )}

            {/* Delete Button */}
            <Button
                variant="ghost"
                size="icon"
                onClick={() => onRemove(filament.id)}
                className="h-8 w-8 text-muted-foreground hover:text-destructive hover:bg-destructive/10 cursor-pointer"
                title={t('filamentRow.removeFilament')}
            >
                <Trash2 className="w-4 h-4" />
            </Button>
        </div>
    );
});

export default FilamentRow;
